/*
 * TRANSLATION FILE (ENGLIGH)
 *
 * Alternative to stringtable.csv which is simpler to install for the mission maker.
 * The token ""%1"" represents a dynamic value generated by the scripts, like a vehicle name.
 *
 * Alternative au stringtable.csv qui est plus simple à installer pour le créateur de mission.
 * Le mot-clé ""%1"" représente une valeur dynamique fournie par les scripts, comme par exemple un nom de véhicule.
 */

STR_R3F_LOG_action_heliporter = "吊装货物";
STR_R3F_LOG_action_heliporter_fait = "货物： ""%1"" 已挂载.";
STR_R3F_LOG_action_heliport_larguer = "投放货物";
STR_R3F_LOG_action_heliport_paradrop = "空投货物";
STR_R3F_LOG_action_heliport_larguer_fait = "货物： ""%1"" 已投放.";
STR_R3F_LOG_action_heliport_attente = "吊装中... (%1)";
STR_R3F_LOG_action_heliport_echec_attente = "吊装中止！在挂钩期间保持悬停。";

STR_R3F_LOG_action_deplacer_objet = "拿起 ""%1""";
STR_R3F_LOG_action_relacher_objet = "放下 ""%1""";
STR_R3F_LOG_action_aligner_pente = "适应坡度";
STR_R3F_LOG_action_aligner_sol = "适应地面";
STR_R3F_LOG_action_aligner_horizon = "水平调整";
STR_R3F_LOG_action_tourner = "左转/右转 (X / C 键)";
STR_R3F_LOG_action_rapprocher = "更近/更远 (F / R 键)";
STR_R3F_LOG_ne_pas_monter_dans_vehicule = "携带此物品时无法进入车辆!";

STR_R3F_LOG_action_charger_deplace = "装载至车辆";
STR_R3F_LOG_action_selectionner_objet_charge = "将 ""%1"" 装载...";
STR_R3F_LOG_action_charger_selection = "... 装载至 ""%1""";
STR_R3F_LOG_action_selectionner_objet_fait = "现在为 ""%1"" 选择装载的载具......";
STR_R3F_LOG_action_charger_en_cours = "正在装载中...";
STR_R3F_LOG_action_charger_fait = """%1"" 已经装载进 ""%2"".";
STR_R3F_LOG_action_charger_pas_assez_de_place = "这辆载具中没有足够的空间容纳这个物体!";

STR_R3F_LOG_action_remorquer_direct = "拖 ""%1""";
STR_R3F_LOG_action_remorquer_deplace = "拖曳物体";
STR_R3F_LOG_action_detacher = "解开拖曳对象";
STR_R3F_LOG_action_detacher_fait = "物体已解除拖曳";
STR_R3F_LOG_action_detacher_impossible_pour_ce_vehicule = "只有驾驶员才能分离这个物体";

STR_R3F_LOG_action_contenu_vehicule = "查看车辆内容";
STR_R3F_LOG_action_decharger_en_cours = "正在卸载中...";
STR_R3F_LOG_action_decharger_fait = """%1"" 已从车辆上卸下";
STR_R3F_LOG_action_decharger_deja_fait = "货物已被卸载!";
STR_R3F_LOG_action_decharger_deplacable_exceptionnel = "释放后，此对象将不再可手动移动。<br/>你确认操作?";

STR_R3F_LOG_action_ouvrir_usine = "打开制造工厂";
STR_R3F_LOG_action_creer_en_cours = "制造正在进行中...";
STR_R3F_LOG_action_creer_fait = """%1"" 已制造完成";
STR_R3F_LOG_action_creer_pas_assez_credits = "工厂没有足够的积分来制造此对象";
STR_R3F_LOG_action_revendre_usine_direct = "退还 ""%1"" 到工厂";
STR_R3F_LOG_action_revendre_usine_deplace = "退还至工厂";
STR_R3F_LOG_action_revendre_usine_selection = "...发回工厂";
STR_R3F_LOG_action_revendre_en_cours = "正在发回工厂...";
STR_R3F_LOG_action_revendre_fait = """%1"" 已被送回工厂";
STR_R3F_LOG_action_revendre_decharger_avant = "当货物内容不为空时，您无法将其寄回!";

STR_R3F_LOG_mutex_action_en_cours = "当前操作未完成!";
STR_R3F_LOG_joueur_dans_objet = """%1""中有一个玩家!";
STR_R3F_LOG_objet_en_cours_transport = """%1"" 已经在运输中!";
STR_R3F_LOG_objet_remorque_en_cours = "错误!“%1”正在拖动另一个对象!";
STR_R3F_LOG_trop_loin = "错误！“%1”太远!";

STR_R3F_LOG_dlg_CV_titre = "车辆库存";
STR_R3F_LOG_dlg_CV_capacite_vehicule = "容量 : %1 / %2";
STR_R3F_LOG_dlg_CV_btn_decharger = "卸载";
STR_R3F_LOG_dlg_CV_btn_fermer = "取消";

STR_R3F_LOG_dlg_LO_titre = "建造工厂";
STR_R3F_LOG_dlg_LO_credits_restants = "剩余弹药 : %1";
STR_R3F_LOG_dlg_LO_btn_creer = "建造";
STR_R3F_LOG_dlg_LO_btn_fermer = "取消";

STR_R3F_LOG_nom_fonctionnalite_proprietes = "财产";
STR_R3F_LOG_nom_fonctionnalite_side = "阵营";
STR_R3F_LOG_nom_fonctionnalite_places = "座位";
STR_R3F_LOG_nom_fonctionnalite_passif = "它可以是:";
STR_R3F_LOG_nom_fonctionnalite_passif_deplace = "由玩家移动";
STR_R3F_LOG_nom_fonctionnalite_passif_heliporte = "已放下";
STR_R3F_LOG_nom_fonctionnalite_passif_remorque = "已拖曳";
STR_R3F_LOG_nom_fonctionnalite_passif_transporte = "已运输";
STR_R3F_LOG_nom_fonctionnalite_passif_transporte_capacite = "装载耗费 %1";
STR_R3F_LOG_nom_fonctionnalite_actif = "它能 :";
STR_R3F_LOG_nom_fonctionnalite_actif_heliporte = "放下";
STR_R3F_LOG_nom_fonctionnalite_actif_remorque = "拖曳";
STR_R3F_LOG_nom_fonctionnalite_actif_transporte = "运输";
STR_R3F_LOG_nom_fonctionnalite_actif_transporte_capacite = "最大装载 %1";

STR_R3F_LOG_deverrouillage_en_cours = "解 锁。。。(%1)";
STR_R3F_LOG_deverrouillage_echec_attente = "解锁已取消！在倒计时期间持续瞄准物体";
STR_R3F_LOG_deverrouillage_succes_attente = "对象已解锁";
STR_R3F_LOG_action_deverrouiller = "解锁 ""%1""";
STR_R3F_LOG_action_deverrouiller_impossible = "对象已锁定";